channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - matplotlib=3.6.2
  - numpy=1.23.5
  - pandas=1.5.1
  - pybedtools=0.9.0
  - pysam=0.19.0
  - scipy=1.9.3
  - setuptools=65.5.1
  - pip
pip:
  - Bio==1.5.3
  - PyPDF2==2.12.1