name: hometools
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - Bio=1.5.3
  - matplotlib=3.6.2=py38h578d9bd_0
  - numpy=1.23.5=py38h7042d01_0
  - pandas=1.5.1=py38h8f669ce_1
  - pybedtools=0.9.0=py38hf4f3596_1
  - PyPDF2=2.12.1
  - pysam=0.19.0=py38h8bf8b8d_0
  - scipy=1.9.3=py38h8ce737c_1
  - setuptools=65.5.1=pyhd8ed1ab_0
