name: Python Package using Conda

on: [push]

jobs:
  build-linux-py38:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        # export $CONDA/bin >> $GITHUB_PATH
        conda init bash
        bash
        $CONDA/bin/python --version
        conda create -n py3.8 python=3.8
        conda activate py3.8
        $CONDA/bin/python --version
        conda deactivate
        $CONDA/bin/python --version
        # conda env update --file environment.yml --name base
        # conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        # conda install pytest
        # python setup.py install
        # $CONDA/bin/pytest