name: Python Package using Conda

on: [push]

jobs:
  build-linux-py38:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        which conda
        which python
        python --version
    - name: Install dependencies
      run: |
        which conda
        which python 
        python --version
        conda env update --file environment.yml --name base
        which conda
        which python 
        python --version